// Auto-generated 2026-06-08 16:39 UTC
window.FOOTBALL_DATA = {
  "UPDATED": "2026-06-08 16:39 UTC",
  "SEASON": "Men's national teams",
  "SOURCE": {
    "name": "Hermes curated snapshot using World Football Elo / MoreElo-style ratings",
    "notes": "Daily-generated static snapshot; update CURRENT_RAW seeds when source rankings move.",
    "through": "2026-06-08 16:39 UTC"
  },
  "IMPORTANCE": 9.0,
  "TEAMS": [
    {
      "id": "argentina",
      "name": "Argentina",
      "teamCode": "ARG",
      "country": "Argentina",
      "logo": "https://flagcdn.com/24x18/ar.png",
      "colors": {
        "primary": "#75AADB",
        "secondary": "#FFFFFF"
      },
      "rank": 1,
      "elo": 2133,
      "eloScore": 100.0,
      "sourceRank": 1,
      "lastMatch": "",
      "worldCups": 3,
      "continentalTitles": 16,
      "note": "Campeón mundial y Copa América; ciclo Scaloni sostiene el pico Elo."
    },
    {
      "id": "spain",
      "name": "Spain",
      "teamCode": "ESP",
      "country": "Spain",
      "logo": "https://flagcdn.com/24x18/es.png",
      "colors": {
        "primary": "#AA151B",
        "secondary": "#F1BF00"
      },
      "rank": 2,
      "elo": 2109,
      "eloScore": 96.4,
      "sourceRank": 2,
      "lastMatch": "",
      "worldCups": 1,
      "continentalTitles": 4,
      "note": "Euro vigente y bloque joven de altísimo rendimiento."
    },
    {
      "id": "france",
      "name": "France",
      "teamCode": "FRA",
      "country": "France",
      "logo": "https://flagcdn.com/24x18/fr.png",
      "colors": {
        "primary": "#002395",
        "secondary": "#ED2939"
      },
      "rank": 3,
      "elo": 2029,
      "eloScore": 84.3,
      "sourceRank": 3,
      "lastMatch": "",
      "worldCups": 2,
      "continentalTitles": 2,
      "note": "Finalista mundial reciente; profundidad ofensiva y defensiva."
    },
    {
      "id": "england",
      "name": "England",
      "teamCode": "ENG",
      "country": "England",
      "logo": "https://flagcdn.com/24x18/gb-eng.png",
      "colors": {
        "primary": "#FFFFFF",
        "secondary": "#CE1124"
      },
      "rank": 4,
      "elo": 2017,
      "eloScore": 82.5,
      "sourceRank": 4,
      "lastMatch": "",
      "worldCups": 1,
      "continentalTitles": 0,
      "note": "Finalista de Euro; rating alto por consistencia ante élite UEFA."
    },
    {
      "id": "portugal",
      "name": "Portugal",
      "teamCode": "POR",
      "country": "Portugal",
      "logo": "https://flagcdn.com/24x18/pt.png",
      "colors": {
        "primary": "#006600",
        "secondary": "#FF0000"
      },
      "rank": 5,
      "elo": 1997,
      "eloScore": 79.5,
      "sourceRank": 5,
      "lastMatch": "",
      "worldCups": 0,
      "continentalTitles": 1,
      "note": "Plantilla top y fase clasificatoria fuerte."
    },
    {
      "id": "brazil",
      "name": "Brazil",
      "teamCode": "BRA",
      "country": "Brazil",
      "logo": "https://flagcdn.com/24x18/br.png",
      "colors": {
        "primary": "#009C3B",
        "secondary": "#FFDF00"
      },
      "rank": 6,
      "elo": 1985,
      "eloScore": 77.7,
      "sourceRank": 6,
      "lastMatch": "",
      "worldCups": 5,
      "continentalTitles": 9,
      "note": "Histórico gigante todavía en zona top 10 pese a ciclo irregular."
    },
    {
      "id": "netherlands",
      "name": "Netherlands",
      "teamCode": "NED",
      "country": "Netherlands",
      "logo": "https://flagcdn.com/24x18/nl.png",
      "colors": {
        "primary": "#FF4F00",
        "secondary": "#21468B"
      },
      "rank": 7,
      "elo": 1976,
      "eloScore": 76.3,
      "sourceRank": 7,
      "lastMatch": "",
      "worldCups": 0,
      "continentalTitles": 1,
      "note": "Bloque estable con muy buen diferencial ante rivales fuertes."
    },
    {
      "id": "germany",
      "name": "Germany",
      "teamCode": "GER",
      "country": "Germany",
      "logo": "https://flagcdn.com/24x18/de.png",
      "colors": {
        "primary": "#000000",
        "secondary": "#DD0000"
      },
      "rank": 8,
      "elo": 1958,
      "eloScore": 73.6,
      "sourceRank": 8,
      "lastMatch": "",
      "worldCups": 4,
      "continentalTitles": 3,
      "note": "Rebote competitivo tras la Euro como anfitrión."
    },
    {
      "id": "italy",
      "name": "Italy",
      "teamCode": "ITA",
      "country": "Italy",
      "logo": "https://flagcdn.com/24x18/it.png",
      "colors": {
        "primary": "#0066B3",
        "secondary": "#009246"
      },
      "rank": 9,
      "elo": 1945,
      "eloScore": 71.7,
      "sourceRank": 9,
      "lastMatch": "",
      "worldCups": 4,
      "continentalTitles": 2,
      "note": "Euro 2020 todavía pesa; ciclo actual busca volver a pico mundial."
    },
    {
      "id": "uruguay",
      "name": "Uruguay",
      "teamCode": "URU",
      "country": "Uruguay",
      "logo": "https://flagcdn.com/24x18/uy.png",
      "colors": {
        "primary": "#75AADB",
        "secondary": "#FFFFFF"
      },
      "rank": 10,
      "elo": 1934,
      "eloScore": 70.0,
      "sourceRank": 10,
      "lastMatch": "",
      "worldCups": 2,
      "continentalTitles": 15,
      "note": "Ciclo Bielsa y resultados CONMEBOL elevan el rating."
    }
  ],
  "ROAD_TO_GLORY": {
    "dynastyThreshold": 42.1,
    "rawDynastyThreshold": 39.4,
    "dynasties": [
      {
        "id": "brazil_1958_1970",
        "name": "Brazil",
        "teamCode": "BRA",
        "country": "Brazil",
        "logo": "https://flagcdn.com/24x18/br.png",
        "colors": {
          "primary": "#009C3B",
          "secondary": "#FFDF00"
        },
        "rank": 1,
        "era": "1958-1970",
        "yearsNo1": 9.2,
        "weeksNo1": 480,
        "matchCount": 118,
        "worldCups": 3,
        "continentalTitles": 0,
        "peakElo": 2160,
        "dynastyScore": 100.0,
        "note": "Pelé, Garrincha, Jairzinho y tres Mundiales en cuatro torneos."
      },
      {
        "id": "brazil_1994_2002",
        "name": "Brazil",
        "teamCode": "BRA",
        "country": "Brazil",
        "logo": "https://flagcdn.com/24x18/br.png",
        "colors": {
          "primary": "#009C3B",
          "secondary": "#FFDF00"
        },
        "rank": 2,
        "era": "1994-2002",
        "yearsNo1": 5.6,
        "weeksNo1": 292,
        "matchCount": 124,
        "worldCups": 2,
        "continentalTitles": 2,
        "peakElo": 2120,
        "dynastyScore": 75.7,
        "note": "Romário, Ronaldo, Rivaldo y Ronaldinho: dos Mundiales y una final más."
      },
      {
        "id": "uruguay_1928_1950",
        "name": "Uruguay",
        "teamCode": "URU",
        "country": "Uruguay",
        "logo": "https://flagcdn.com/24x18/uy.png",
        "colors": {
          "primary": "#75AADB",
          "secondary": "#FFFFFF"
        },
        "rank": 3,
        "era": "1928-1950",
        "yearsNo1": 4.5,
        "weeksNo1": 234,
        "matchCount": 65,
        "worldCups": 2,
        "continentalTitles": 2,
        "peakElo": 2065,
        "dynastyScore": 68.3,
        "note": "Fundadores del fútbol moderno: primer Mundial, Copa Am 35/42 y el Maracanazo."
      },
      {
        "id": "argentina_2021_now",
        "name": "Argentina",
        "teamCode": "ARG",
        "country": "Argentina",
        "logo": "https://flagcdn.com/24x18/ar.png",
        "colors": {
          "primary": "#75AADB",
          "secondary": "#FFFFFF"
        },
        "rank": 4,
        "era": "2021-present",
        "yearsNo1": 5.4,
        "weeksNo1": 166,
        "matchCount": 58,
        "worldCups": 1,
        "continentalTitles": 2,
        "peakElo": 2133,
        "dynastyScore": 60.4,
        "note": "Copa América, Mundial y nueva Copa América en una racha larguísima sin derrota."
      },
      {
        "id": "argentina_1978_1986",
        "name": "Argentina",
        "teamCode": "ARG",
        "country": "Argentina",
        "logo": "https://flagcdn.com/24x18/ar.png",
        "colors": {
          "primary": "#75AADB",
          "secondary": "#FFFFFF"
        },
        "rank": 5,
        "era": "1978-1986",
        "yearsNo1": 3.5,
        "weeksNo1": 182,
        "matchCount": 88,
        "worldCups": 2,
        "continentalTitles": 1,
        "peakElo": 2095,
        "dynastyScore": 58.7,
        "note": "Kempes 78 y Maradona 86: dos Mundiales con estilos y leyendas opuestos."
      },
      {
        "id": "spain_2008_2012",
        "name": "Spain",
        "teamCode": "ESP",
        "country": "Spain",
        "logo": "https://flagcdn.com/24x18/es.png",
        "colors": {
          "primary": "#AA151B",
          "secondary": "#F1BF00"
        },
        "rank": 6,
        "era": "2008-2012",
        "yearsNo1": 4.1,
        "weeksNo1": 214,
        "matchCount": 72,
        "worldCups": 1,
        "continentalTitles": 2,
        "peakElo": 2164,
        "dynastyScore": 54.4,
        "note": "Euro-Mundial-Euro: la dinastía de posesión más limpia de la era moderna."
      },
      {
        "id": "italy_1934_1938",
        "name": "Italy",
        "teamCode": "ITA",
        "country": "Italy",
        "logo": "https://flagcdn.com/24x18/it.png",
        "colors": {
          "primary": "#0066B3",
          "secondary": "#009246"
        },
        "rank": 7,
        "era": "1934-1938",
        "yearsNo1": 3.5,
        "weeksNo1": 182,
        "matchCount": 46,
        "worldCups": 2,
        "continentalTitles": 0,
        "peakElo": 2070,
        "dynastyScore": 52.7,
        "note": "Primer bicampeón mundial; dominio de los años treinta."
      },
      {
        "id": "germany_1980_1990",
        "name": "Germany",
        "teamCode": "GER",
        "country": "Germany",
        "logo": "https://flagcdn.com/24x18/de.png",
        "colors": {
          "primary": "#000000",
          "secondary": "#DD0000"
        },
        "rank": 8,
        "era": "1980-1990",
        "yearsNo1": 4.0,
        "weeksNo1": 208,
        "matchCount": 112,
        "worldCups": 1,
        "continentalTitles": 1,
        "peakElo": 2095,
        "dynastyScore": 46.6,
        "note": "Euro 80, tres finales mundialistas en ocho años y campeones en Italia 90."
      },
      {
        "id": "germany_1972_1976",
        "name": "Germany",
        "teamCode": "GER",
        "country": "Germany",
        "logo": "https://flagcdn.com/24x18/de.png",
        "colors": {
          "primary": "#000000",
          "secondary": "#DD0000"
        },
        "rank": 9,
        "era": "1972-1976",
        "yearsNo1": 3.7,
        "weeksNo1": 193,
        "matchCount": 61,
        "worldCups": 1,
        "continentalTitles": 1,
        "peakElo": 2105,
        "dynastyScore": 45.4,
        "note": "Beckenbauer y Müller sostienen Euro 72, Mundial 74 y final Euro 76."
      },
      {
        "id": "france_1998_2001",
        "name": "France",
        "teamCode": "FRA",
        "country": "France",
        "logo": "https://flagcdn.com/24x18/fr.png",
        "colors": {
          "primary": "#002395",
          "secondary": "#ED2939"
        },
        "rank": 10,
        "era": "1998-2001",
        "yearsNo1": 3.0,
        "weeksNo1": 156,
        "matchCount": 55,
        "worldCups": 1,
        "continentalTitles": 1,
        "peakElo": 2118,
        "dynastyScore": 42.1,
        "note": "Zidane, Desailly, Thuram, Henry: Mundial y Euro consecutivos."
      }
    ],
    "currentContenders": [
      {
        "id": "argentina",
        "name": "Argentina",
        "teamCode": "ARG",
        "country": "Argentina",
        "logo": "https://flagcdn.com/24x18/ar.png",
        "colors": {
          "primary": "#75AADB",
          "secondary": "#FFFFFF"
        },
        "rank": 1,
        "elo": 2133,
        "eloScore": 100.0,
        "sourceRank": 1,
        "lastMatch": "",
        "worldCups": 3,
        "continentalTitles": 16,
        "note": "Ya está proyectada en zona top 10 si sostiene el ciclo",
        "dynastyPotential": 100.0,
        "rawDynastyPotential": 121.9,
        "gapToDynastyTop10": 0.0,
        "cycleYears": 3.2,
        "currentWorldCups": 1,
        "currentContinentalTitles": 2,
        "recentFinals": 3,
        "ageCurve": 0.78
      },
      {
        "id": "spain",
        "name": "Spain",
        "teamCode": "ESP",
        "country": "Spain",
        "logo": "https://flagcdn.com/24x18/es.png",
        "colors": {
          "primary": "#AA151B",
          "secondary": "#F1BF00"
        },
        "rank": 2,
        "elo": 2109,
        "eloScore": 96.4,
        "sourceRank": 2,
        "lastMatch": "",
        "worldCups": 1,
        "continentalTitles": 4,
        "note": "Ya está proyectada en zona top 10 si sostiene el ciclo",
        "dynastyPotential": 100.0,
        "rawDynastyPotential": 57.1,
        "gapToDynastyTop10": 0.0,
        "cycleYears": 1.6,
        "currentWorldCups": 0,
        "currentContinentalTitles": 1,
        "recentFinals": 1,
        "ageCurve": 0.96
      },
      {
        "id": "france",
        "name": "France",
        "teamCode": "FRA",
        "country": "France",
        "logo": "https://flagcdn.com/24x18/fr.png",
        "colors": {
          "primary": "#002395",
          "secondary": "#ED2939"
        },
        "rank": 3,
        "elo": 2029,
        "eloScore": 84.3,
        "sourceRank": 3,
        "lastMatch": "",
        "worldCups": 2,
        "continentalTitles": 2,
        "note": "Ya está proyectada en zona top 10 si sostiene el ciclo",
        "dynastyPotential": 100.0,
        "rawDynastyPotential": 87.8,
        "gapToDynastyTop10": 0.0,
        "cycleYears": 2.8,
        "currentWorldCups": 1,
        "currentContinentalTitles": 0,
        "recentFinals": 2,
        "ageCurve": 0.9
      },
      {
        "id": "england",
        "name": "England",
        "teamCode": "ENG",
        "country": "England",
        "logo": "https://flagcdn.com/24x18/gb-eng.png",
        "colors": {
          "primary": "#FFFFFF",
          "secondary": "#CE1124"
        },
        "rank": 4,
        "elo": 2017,
        "eloScore": 82.5,
        "sourceRank": 4,
        "lastMatch": "",
        "worldCups": 1,
        "continentalTitles": 0,
        "note": "Ya está proyectada en zona top 10 si sostiene el ciclo",
        "dynastyPotential": 100.0,
        "rawDynastyPotential": 54.8,
        "gapToDynastyTop10": 0.0,
        "cycleYears": 2.4,
        "currentWorldCups": 0,
        "currentContinentalTitles": 0,
        "recentFinals": 2,
        "ageCurve": 0.88
      },
      {
        "id": "portugal",
        "name": "Portugal",
        "teamCode": "POR",
        "country": "Portugal",
        "logo": "https://flagcdn.com/24x18/pt.png",
        "colors": {
          "primary": "#006600",
          "secondary": "#FF0000"
        },
        "rank": 5,
        "elo": 1997,
        "eloScore": 79.5,
        "sourceRank": 5,
        "lastMatch": "",
        "worldCups": 0,
        "continentalTitles": 1,
        "note": "A 4.0 puntos brutos del umbral dinástico",
        "dynastyPotential": 89.8,
        "rawDynastyPotential": 35.4,
        "gapToDynastyTop10": 4.0,
        "cycleYears": 1.8,
        "currentWorldCups": 0,
        "currentContinentalTitles": 0,
        "recentFinals": 0,
        "ageCurve": 0.86
      },
      {
        "id": "brazil",
        "name": "Brazil",
        "teamCode": "BRA",
        "country": "Brazil",
        "logo": "https://flagcdn.com/24x18/br.png",
        "colors": {
          "primary": "#009C3B",
          "secondary": "#FFDF00"
        },
        "rank": 6,
        "elo": 1985,
        "eloScore": 77.7,
        "sourceRank": 6,
        "lastMatch": "",
        "worldCups": 5,
        "continentalTitles": 9,
        "note": "A 5.0 puntos brutos del umbral dinástico",
        "dynastyPotential": 87.4,
        "rawDynastyPotential": 34.5,
        "gapToDynastyTop10": 5.0,
        "cycleYears": 1.2,
        "currentWorldCups": 0,
        "currentContinentalTitles": 0,
        "recentFinals": 1,
        "ageCurve": 0.84
      },
      {
        "id": "netherlands",
        "name": "Netherlands",
        "teamCode": "NED",
        "country": "Netherlands",
        "logo": "https://flagcdn.com/24x18/nl.png",
        "colors": {
          "primary": "#FF4F00",
          "secondary": "#21468B"
        },
        "rank": 7,
        "elo": 1976,
        "eloScore": 76.3,
        "sourceRank": 7,
        "lastMatch": "",
        "worldCups": 0,
        "continentalTitles": 1,
        "note": "A 9.3 puntos brutos del umbral dinástico",
        "dynastyPotential": 76.4,
        "rawDynastyPotential": 30.1,
        "gapToDynastyTop10": 9.3,
        "cycleYears": 1.4,
        "currentWorldCups": 0,
        "currentContinentalTitles": 0,
        "recentFinals": 0,
        "ageCurve": 0.85
      },
      {
        "id": "uruguay",
        "name": "Uruguay",
        "teamCode": "URU",
        "country": "Uruguay",
        "logo": "https://flagcdn.com/24x18/uy.png",
        "colors": {
          "primary": "#75AADB",
          "secondary": "#FFFFFF"
        },
        "rank": 10,
        "elo": 1934,
        "eloScore": 70.0,
        "sourceRank": 10,
        "lastMatch": "",
        "worldCups": 2,
        "continentalTitles": 15,
        "note": "A 12.9 puntos brutos del umbral dinástico",
        "dynastyPotential": 67.2,
        "rawDynastyPotential": 26.5,
        "gapToDynastyTop10": 12.9,
        "cycleYears": 1.3,
        "currentWorldCups": 0,
        "currentContinentalTitles": 0,
        "recentFinals": 0,
        "ageCurve": 0.83
      },
      {
        "id": "germany",
        "name": "Germany",
        "teamCode": "GER",
        "country": "Germany",
        "logo": "https://flagcdn.com/24x18/de.png",
        "colors": {
          "primary": "#000000",
          "secondary": "#DD0000"
        },
        "rank": 8,
        "elo": 1958,
        "eloScore": 73.6,
        "sourceRank": 8,
        "lastMatch": "",
        "worldCups": 4,
        "continentalTitles": 3,
        "note": "A 14.7 puntos brutos del umbral dinástico",
        "dynastyPotential": 62.6,
        "rawDynastyPotential": 24.7,
        "gapToDynastyTop10": 14.7,
        "cycleYears": 1.0,
        "currentWorldCups": 0,
        "currentContinentalTitles": 0,
        "recentFinals": 0,
        "ageCurve": 0.82
      },
      {
        "id": "italy",
        "name": "Italy",
        "teamCode": "ITA",
        "country": "Italy",
        "logo": "https://flagcdn.com/24x18/it.png",
        "colors": {
          "primary": "#0066B3",
          "secondary": "#009246"
        },
        "rank": 9,
        "elo": 1945,
        "eloScore": 71.7,
        "sourceRank": 9,
        "lastMatch": "",
        "worldCups": 4,
        "continentalTitles": 2,
        "note": "A 17.0 puntos brutos del umbral dinástico",
        "dynastyPotential": 56.8,
        "rawDynastyPotential": 22.4,
        "gapToDynastyTop10": 17.0,
        "cycleYears": 0.9,
        "currentWorldCups": 0,
        "currentContinentalTitles": 0,
        "recentFinals": 0,
        "ageCurve": 0.78
      }
    ]
  }
};
