// Auto-generated 2026-06-03 22:35 UTC
window.SUMO_DATA = {
  "UPDATED": "2026-06-03 22:35 UTC",
  "LEGENDS": [
    {
      "id": "hakuho",
      "name": "Hakuho",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 100.0,
      "stats": {
        "yusho": 45,
        "yokozuna_basho": 84,
        "birth": 1985,
        "yok_start": 2007,
        "yok_end": 2021
      },
      "prevRank": null
    },
    {
      "id": "taiho",
      "name": "Taiho",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 70.8,
      "stats": {
        "yusho": 32,
        "yokozuna_basho": 58,
        "birth": 1940,
        "yok_start": 1961,
        "yok_end": 1971
      },
      "prevRank": null
    },
    {
      "id": "chiyonofuji",
      "name": "Chiyonofuji",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 68.9,
      "stats": {
        "yusho": 31,
        "yokozuna_basho": 58,
        "birth": 1955,
        "yok_start": 1981,
        "yok_end": 1991
      },
      "prevRank": null
    },
    {
      "id": "asashoryu",
      "name": "Asashoryu",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 58.1,
      "stats": {
        "yusho": 25,
        "yokozuna_basho": 60,
        "birth": 1980,
        "yok_start": 2003,
        "yok_end": 2010
      },
      "prevRank": null
    },
    {
      "id": "kitanoumi",
      "name": "Kitanoumi",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 56.7,
      "stats": {
        "yusho": 24,
        "yokozuna_basho": 63,
        "birth": 1953,
        "yok_start": 1974,
        "yok_end": 1985
      },
      "prevRank": null
    },
    {
      "id": "musashimaru",
      "name": "Musashimaru",
      "country": "USA",
      "logo": "https://flagcdn.com/24x18/us.png",
      "teamCode": "USA",
      "primary": "#B22234",
      "secondary": "#FFFFFF",
      "legendScore": 29.6,
      "stats": {
        "yusho": 12,
        "yokozuna_basho": 38,
        "birth": 1971,
        "yok_start": 1999,
        "yok_end": 2003
      },
      "prevRank": null
    },
    {
      "id": "futabayama",
      "name": "Futabayama",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 29.0,
      "stats": {
        "yusho": 12,
        "yokozuna_basho": 35,
        "birth": 1912,
        "yok_start": 1936,
        "yok_end": 1943
      },
      "prevRank": null
    },
    {
      "id": "akebono",
      "name": "Akebono",
      "country": "USA",
      "logo": "https://flagcdn.com/24x18/us.png",
      "teamCode": "USA",
      "primary": "#B22234",
      "secondary": "#FFFFFF",
      "legendScore": 27.3,
      "stats": {
        "yusho": 11,
        "yokozuna_basho": 36,
        "birth": 1969,
        "yok_start": 1993,
        "yok_end": 2001
      },
      "prevRank": null
    },
    {
      "id": "harumafuji",
      "name": "Harumafuji",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 22.5,
      "stats": {
        "yusho": 9,
        "yokozuna_basho": 30,
        "birth": 1984,
        "yok_start": 2012,
        "yok_end": 2017
      },
      "prevRank": null
    },
    {
      "id": "terunofuji",
      "name": "Terunofuji",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 22.1,
      "stats": {
        "yusho": 10,
        "yokozuna_basho": 18,
        "birth": 1991,
        "yok_start": 2021,
        "yok_end": 2024
      },
      "prevRank": null
    },
    {
      "id": "kakuryu",
      "name": "Kakuryu",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 19.1,
      "stats": {
        "yusho": 6,
        "yokozuna_basho": 42,
        "birth": 1985,
        "yok_start": 2014,
        "yok_end": 2021
      },
      "prevRank": null
    },
    {
      "id": "onosato",
      "name": "Onosato",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 10.5,
      "stats": {
        "yusho": 5,
        "yokozuna_basho": 6,
        "birth": 2000,
        "yok_start": 2025,
        "yok_end": null
      },
      "prevRank": null
    },
    {
      "id": "hoshoryu",
      "name": "Hoshoryu",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 7.1,
      "stats": {
        "yusho": 3,
        "yokozuna_basho": 8,
        "birth": 1999,
        "yok_start": 2024,
        "yok_end": null
      },
      "prevRank": null
    }
  ],
  "BASHO_ID": "202605",
  "BASHO_INFO": {
    "id": "202605",
    "startDate": "2026-05-10T00:00:00Z",
    "endDate": "2026-05-24T00:00:00Z",
    "winner": "Wakatakakage"
  },
  "BANZUKE": [
    {
      "side": "East",
      "rankValue": 101,
      "rankLabel": "Yokozuna 1 East",
      "name": "Hoshoryu",
      "rikishiID": 19,
      "wins": 0,
      "losses": 2,
      "absences": 13,
      "rankShort": "Yokozuna",
      "yusho": 3,
      "legendScore": 7.1,
      "age": 27
    },
    {
      "side": "West",
      "rankValue": 101,
      "rankLabel": "Yokozuna 1 West",
      "name": "Onosato",
      "rikishiID": 8850,
      "wins": 0,
      "losses": 0,
      "absences": 15,
      "rankShort": "Yokozuna",
      "yusho": 5,
      "legendScore": 10.5,
      "age": 25
    },
    {
      "side": "East",
      "rankValue": 201,
      "rankLabel": "Ozeki 1 East",
      "name": "Kotozakura",
      "rikishiID": 20,
      "wins": 3,
      "losses": 9,
      "absences": 3,
      "rankShort": "Ozeki",
      "yusho": 1,
      "legendScore": 1.9,
      "age": 28
    },
    {
      "side": "West",
      "rankValue": 201,
      "rankLabel": "Ozeki 1 West",
      "name": "Aonishiki",
      "rikishiID": 8854,
      "wins": 0,
      "losses": 0,
      "absences": 15,
      "rankShort": "Ozeki",
      "yusho": 2,
      "legendScore": 3.7,
      "age": 22
    },
    {
      "side": "East",
      "rankValue": 202,
      "rankLabel": "Ozeki 2 East",
      "name": "Kirishima",
      "rikishiID": 7,
      "wins": 12,
      "losses": 3,
      "absences": 0,
      "rankShort": "Ozeki",
      "yusho": 3,
      "legendScore": 5.6,
      "age": 30
    },
    {
      "side": "East",
      "rankValue": 301,
      "rankLabel": "Sekiwake 1 East",
      "name": "Atamifuji",
      "rikishiID": 74,
      "wins": 9,
      "losses": 6,
      "absences": 0,
      "rankShort": "Sekiwake",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 23
    },
    {
      "side": "West",
      "rankValue": 301,
      "rankLabel": "Sekiwake 1 West",
      "name": "Kotoshoho",
      "rikishiID": 8,
      "wins": 9,
      "losses": 6,
      "absences": 0,
      "rankShort": "Sekiwake",
      "yusho": 1,
      "legendScore": 1.9,
      "age": 26
    },
    {
      "side": "East",
      "rankValue": 401,
      "rankLabel": "Komusubi 1 East",
      "name": "Wakatakakage",
      "rikishiID": 12,
      "wins": 12,
      "losses": 3,
      "absences": 0,
      "rankShort": "Komusubi",
      "yusho": 2,
      "legendScore": 3.7,
      "age": 31
    },
    {
      "side": "West",
      "rankValue": 401,
      "rankLabel": "Komusubi 1 West",
      "name": "Takayasu",
      "rikishiID": 44,
      "wins": 2,
      "losses": 2,
      "absences": 11,
      "rankShort": "Komusubi",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 36
    },
    {
      "side": "East",
      "rankValue": 501,
      "rankLabel": "Maegashira 1 East",
      "name": "Fujinokawa",
      "rikishiID": 615,
      "wins": 7,
      "losses": 8,
      "absences": 0,
      "rankShort": "Maegashira 1",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 21
    },
    {
      "side": "West",
      "rankValue": 501,
      "rankLabel": "Maegashira 1 West",
      "name": "Takanosho",
      "rikishiID": 37,
      "wins": 7,
      "losses": 8,
      "absences": 0,
      "rankShort": "Maegashira 1",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 31
    },
    {
      "side": "East",
      "rankValue": 502,
      "rankLabel": "Maegashira 2 East",
      "name": "Yoshinofuji",
      "rikishiID": 8857,
      "wins": 11,
      "losses": 4,
      "absences": 0,
      "rankShort": "Maegashira 2",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 24
    },
    {
      "side": "West",
      "rankValue": 502,
      "rankLabel": "Maegashira 2 West",
      "name": "Ichiyamamoto",
      "rikishiID": 11,
      "wins": 6,
      "losses": 9,
      "absences": 0,
      "rankShort": "Maegashira 2",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 32
    },
    {
      "side": "East",
      "rankValue": 503,
      "rankLabel": "Maegashira 3 East",
      "name": "Hiradoumi",
      "rikishiID": 24,
      "wins": 7,
      "losses": 8,
      "absences": 0,
      "rankShort": "Maegashira 3",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 26
    },
    {
      "side": "West",
      "rankValue": 503,
      "rankLabel": "Maegashira 3 West",
      "name": "Oho",
      "rikishiID": 41,
      "wins": 9,
      "losses": 6,
      "absences": 0,
      "rankShort": "Maegashira 3",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 26
    },
    {
      "side": "East",
      "rankValue": 504,
      "rankLabel": "Maegashira 4 East",
      "name": "Daieisho",
      "rikishiID": 9,
      "wins": 7,
      "losses": 8,
      "absences": 0,
      "rankShort": "Maegashira 4",
      "yusho": 1,
      "legendScore": 1.9,
      "age": 32
    },
    {
      "side": "West",
      "rankValue": 504,
      "rankLabel": "Maegashira 4 West",
      "name": "Gonoyama",
      "rikishiID": 56,
      "wins": 8,
      "losses": 7,
      "absences": 0,
      "rankShort": "Maegashira 4",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 28
    },
    {
      "side": "East",
      "rankValue": 505,
      "rankLabel": "Maegashira 5 East",
      "name": "Wakamotoharu",
      "rikishiID": 13,
      "wins": 5,
      "losses": 10,
      "absences": 0,
      "rankShort": "Maegashira 5",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 32
    },
    {
      "side": "West",
      "rankValue": 505,
      "rankLabel": "Maegashira 5 West",
      "name": "Shodai",
      "rikishiID": 33,
      "wins": 6,
      "losses": 9,
      "absences": 0,
      "rankShort": "Maegashira 5",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 34
    },
    {
      "side": "East",
      "rankValue": 506,
      "rankLabel": "Maegashira 6 East",
      "name": "Churanoumi",
      "rikishiID": 71,
      "wins": 9,
      "losses": 6,
      "absences": 0,
      "rankShort": "Maegashira 6",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 33
    }
  ],
  "IMPORTANCE": 8.5
};
